### PR TITLE
Console: Allow adding description when creating access keys

### PR DESCRIPTION
**Pull request by jbtrystram**
When clicking on the create button: 

image

Then a confirmation modal : 
image

### CODE REVIEW

**Comment by jbtrystram** [comment]
> I also saw (can't find it now) a checkbox (with "I copied the token and know that I can't get it back") plus disabling the close button as long as the checkbox is not ticked.

I don't like this, it feels like something frustrating that i would not really read :D 
The yellow box with a warning that yiu showed is good however, it attract the eyes and get the the point across.

**Comment by ctron** [comment]
IIRC Patternfly had an "inline" variant for this: https://www.patternfly.org/v4/components/alert/#inline-types

Not sure we support it yet.

**Review by ctron — APPROVED** [review]
I any case +1 for merging!

**Comment by jbtrystram** [comment]
@ctron here is the redesigned modal : 
image

Thanks for the feedback !

**Pull request merged**
