### PR TITLE
Resolve clippy pedantry

### PR DESCRIPTION
**Pull request by jcrossley3**
Reducing some noise in the build output... let's see if I broke anything important!

### CODE REVIEW

**Comment by ctron** [comment]
That is awesome! I am bit concerned of dropping the dependency on `actix-http`. What happened in the past was, that they did release a new beta version, which was not compatible anymore with the beta version of `actix-web` and so the build failed. Adding an explicit, pinned version solved this issue.

**Comment by jcrossley3** [comment]
> That is awesome! I am bit concerned of dropping the dependency on `actix-http`. What happened in the past was, that they did release a new beta version, which was not compatible anymore with the beta version of `actix-web` and so the build failed. Adding an explicit, pinned version solved this issue.

As long as we're pinning `actix-web` to a specific beta version, won't its transitive deps, e.g. `actix-http` be pinned, too? I'm mostly just trying to reduce the surface area of things we need to change each time we update `actix-web`. Seems weird to have to pin its deps if we're already pinning it. (apologies if i'm misunderstanding)

**Comment by ctron** [comment]
To my understanding, no. It only pins the dependency to the directly referenced one. For the reference dependency, normal resolution rules apply.

As actix-web references `actix-http = "3.0.0-beta.18"`, this is a non-pinned version and may be upgraded: https://github.com/actix/actix-web/blob/master/Cargo.toml#L80

**Pull request merged**
