### PR TITLE
build: split off console-frontend

### PR DESCRIPTION
**Pull request by ctron**
This allows setting dedicated link/profile options for the console
frontend, reducing the size of about 1MiB, keeping the compile times
for the overall project reasonable.

### CODE REVIEW

**Comment by jbtrystram** [comment]
If I am correct `make build` won't build the console anymore ?

**Comment by ctron** [comment]
It should.

**Review by lulf — APPROVED** [review]
Shouldn't

**Comment by ctron** [comment]
Make targets: build -> host-build -> container-build -> webpack-build

And that should build the frontend.

**Comment by ctron** [comment]
> Shouldn't

`make build` should build just everything IMHO.

`make cargo-build` would only build the non-frontend stuff (as before the change).

e.g. `make -C <module> build images` would only build a single container (as before).

`make frontend` should only build the frontend (as before).

The only thing that is different now, is that the `console-frontend` is no longer part of the global workspace.

**Comment by lulf** [comment]
@ctron :laughing: that was a stray word that I was typing related to the [workspace] not being present in console-frontend/Cargo.toml so I wondered why it would even build. Then I saw it did build and I deleted almost all of the comment before hitting comment.

**Pull request merged**
